import fs from "fs";
import path from "path";
import os from "os";
import { fileURLToPath } from "url";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const cucumberHtmlReporter = require("multiple-cucumber-html-reporter");

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const frameworkRoot = path.resolve(__dirname, "../../..");

// --- Path Constants ---
export const ALLURE_RESULTS_DIR = path.join(frameworkRoot, "allure-results");
export const ALLURE_REPORT_DIR = path.join(frameworkRoot, "allure-report");
export const REPORTS_ROOT = path.join(frameworkRoot, "reports");
export const CUCUMBER_REPORT_DIR = path.join(REPORTS_ROOT, "html-report");
export const CUCUMBER_JSON_FILE = path.join(REPORTS_ROOT, "cucumber-report.json");
export const HISTORY_DIR = path.join(frameworkRoot, "report-history");
export const DASHBOARD_PATH = path.join(HISTORY_DIR, "index.html");

// --- Helper Utilities ---

/**
 * Recursively copy a directory.
 */
export function copyDirSync(src, dest) {
  if (!fs.existsSync(src)) return;
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirSync(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

/**
 * Check if a directory exists and has at least one file.
 */
export function hasContent(dir) {
  if (!fs.existsSync(dir)) return false;
  return fs.readdirSync(dir).length > 0;
}

/**
 * Generate a filesystem-safe, sortable timestamp string.
 */
export function getTimestamp() {
  const now = new Date();
  const pad = (n) => String(n).padStart(2, "0");
  return [
    now.getFullYear(),
    "-", pad(now.getMonth() + 1),
    "-", pad(now.getDate()),
    "_",
    pad(now.getHours()),
    "-", pad(now.getMinutes()),
    "-", pad(now.getSeconds())
  ].join("");
}

/**
 * Derive a descriptive run name from context.
 */
export function getRunName() {
  if (fs.existsSync(CUCUMBER_JSON_FILE)) {
    try {
      const data = JSON.parse(fs.readFileSync(CUCUMBER_JSON_FILE, "utf-8"));
      const allTags = new Set();
      data.forEach(feature => {
        if (feature.tags) feature.tags.forEach(t => allTags.add(t.name));
      });
      if (allTags.size > 0) {
        return Array.from(allTags).join("-").replace(/@/g, "").replace(/[^a-zA-Z0-9_-]/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "");
      }
      if (data.length === 1 && data[0].name) {
        return data[0].name.replace(/[^a-zA-Z0-9_-]/g, " ").trim().replace(/\s+/g, "-");
      }
    } catch (e) {}
  }
  if (process.env.TAGS) return process.env.TAGS.replace(/@/g, "").replace(/[^a-zA-Z0-9_-]/g, "-");
  if (process.env.FEATURE_PATH) return path.basename(process.env.FEATURE_PATH, ".feature").replace(/[^a-zA-Z0-9_-]/g, "-");
  return "test-run";
}

// --- Main Exported Actions ---

/**
 * Clean old test results and reports.
 */
export function cleanResults() {
  console.log("\n🧹 Cleaning old test results and reports...");
  const dirs = [ALLURE_RESULTS_DIR, ALLURE_REPORT_DIR, REPORTS_ROOT];
  dirs.forEach(dir => {
    if (fs.existsSync(dir)) fs.rmSync(dir, { recursive: true, force: true });
    fs.mkdirSync(dir, { recursive: true });
  });
  console.log("✅ Old reports cleaned successfully!\n");
}

/**
 * Generate Cucumber HTML report.
 */
export function generateCucumberReport() {
  if (!fs.existsSync(CUCUMBER_JSON_FILE)) {
    console.warn("\n⚠️  No cucumber-report.json found. Skipping report generation.\n");
    return;
  }

  const browser = process.env.BROWSER || "chromium";
  const platform = process.platform === "win32" ? "windows" : process.platform;

  cucumberHtmlReporter.generate({
    jsonDir: REPORTS_ROOT,
    reportPath: CUCUMBER_REPORT_DIR,
    metadata: {
      browser: { name: browser, version: "latest" },
      device: "Local test machine",
      platform: { name: platform, version: os.release() },
    },
    customData: {
      title: "Run Info",
      data: [
        { label: "Project", value: getRunName() },
        { label: "Generated", value: new Date().toLocaleString() },
      ],
    },
    pageFooter: '<div class="created-by"><p>Generated by TS Playwright Cucumber Framework</p></div>',
  });
  console.log("✅ Cucumber HTML report generated at: " + path.join(CUCUMBER_REPORT_DIR, "index.html"));
}

/**
 * Archive existing reports.
 */
export function archiveReports() {
  if (!hasContent(ALLURE_REPORT_DIR) && !hasContent(CUCUMBER_REPORT_DIR)) {
    return null;
  }

  const runName = getRunName();
  const timestamp = getTimestamp();
  const archiveDir = path.join(HISTORY_DIR, `${runName}_${timestamp}`);
  fs.mkdirSync(archiveDir, { recursive: true });

  if (hasContent(ALLURE_REPORT_DIR)) copyDirSync(ALLURE_REPORT_DIR, path.join(archiveDir, "allure"));
  if (hasContent(CUCUMBER_REPORT_DIR)) copyDirSync(CUCUMBER_REPORT_DIR, path.join(archiveDir, "cucumber"));

  console.log(`\n📦 REPORT ARCHIVED: ${archiveDir}`);
  generateHistoryDashboard();
  return archiveDir;
}

/**
 * List history in terminal.
 */
export function listHistory() {
  if (!fs.existsSync(HISTORY_DIR)) {
    console.log("\n📂 No report history found.");
    return;
  }
  const entries = fs.readdirSync(HISTORY_DIR, { withFileTypes: true })
    .filter(e => e.isDirectory())
    .map(e => e.name)
    .sort((a, b) => b.localeCompare(a));
    
  console.log("\n📋 REPORT HISTORY:");
  entries.forEach((e, i) => console.log(`  ${i + 1}. ${e}`));
}

/**
 * Generate index.html dashboard for history.
 */
export function generateHistoryDashboard() {
  if (!fs.existsSync(HISTORY_DIR)) return;
  const entries = fs.readdirSync(HISTORY_DIR, { withFileTypes: true })
    .filter(e => e.isDirectory())
    .map(e => e.name)
    .sort((a, b) => b.localeCompare(a));

  const runs = entries.map(folder => {
      const archivePath = path.join(HISTORY_DIR, folder);
      return {
          folder,
          hasAllure: fs.existsSync(path.join(archivePath, "allure", "index.html")),
          hasCucumber: fs.existsSync(path.join(archivePath, "cucumber", "index.html"))
      };
  });

  const html = `<!DOCTYPE html><html><head><title>Test History</title>
  <style>
    body { font-family: sans-serif; background: #0f172a; color: #fff; padding: 2rem; }
    .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 1rem; }
    .card { background: #1e293b; padding: 1rem; border-radius: 0.5rem; border: 1px solid #334155; }
    a { color: #38bdf8; text-decoration: none; margin-right: 1rem; }
    a:hover { text-decoration: underline; }
  </style></head><body>
  <h1>Test History Dashboard</h1>
  <div class="grid">${runs.map(r => `
    <div class="card">
      <h3>${r.folder}</h3>
      ${r.hasAllure ? `<a href="./${r.folder}/allure/index.html">Allure</a>` : ""}
      ${r.hasCucumber ? `<a href="./${r.folder}/cucumber/index.html">Cucumber</a>` : ""}
    </div>`).join("")}</div>
  </body></html>`;

  fs.writeFileSync(DASHBOARD_PATH, html);
}

/**
 * Print summary of final paths.
 */
export function printSummary() {
  console.log("\n======================================");
  console.log(" Test Execution Completed");
  console.log(` 📊 Allure: ${path.join(ALLURE_REPORT_DIR, "index.html")}`);
  console.log(` 🥒 Cucumber: ${path.join(CUCUMBER_REPORT_DIR, "index.html")}`);
  console.log("======================================\n");
}

// --- CLI Handler ---

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const args = process.argv;
  if (args.includes("--clean")) cleanResults();
  if (args.includes("--archive")) archiveReports();
  if (args.includes("--history")) listHistory();
  if (args.includes("--dashboard")) generateHistoryDashboard();
  if (args.includes("--cucumber")) generateCucumberReport();
  if (args.includes("--print")) printSummary();
  if (args.includes("--open-cucumber")) {
    const html = path.join(CUCUMBER_REPORT_DIR, "index.html");
    if (fs.existsSync(html)) {
      const cmd = process.platform === "win32" ? "start" : process.platform === "darwin" ? "open" : "xdg-open";
      spawn(cmd, [html], { shell: true });
    }
  }
}
