import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import path from "node:path";
import os from "node:os";
import fs from "node:fs";
import { archiveReports } from "./archiveReports.js";

const require = createRequire(import.meta.url);
const report = require("multiple-cucumber-html-reporter");

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const frameworkRoot = path.resolve(__dirname, "../..");

const jsonDir = path.join(frameworkRoot, "reports");
const reportPath = path.join(frameworkRoot, "reports", "html-report");
const jsonFile = path.join(jsonDir, "cucumber-report.json");

if (!fs.existsSync(jsonFile)) {
  console.warn("\n⚠️  No cucumber-report.json found at:\n  " + jsonFile);
  console.warn("   Run tests first to generate results.\n");
  process.exit(0);
}

const browser = process.env.BROWSER || "chromium";
const platformMap = { win32: "windows", darwin: "mac", linux: "linux" };
const platformName = platformMap[os.platform()] ?? os.platform();
const platformVersion = os.release();

/**
 * Dynamically determines the display name for the report.
 * Extracts tags or feature name from the JSON report or environment.
 */
function getRunDisplayName() {
  if (fs.existsSync(jsonFile)) {
    try {
      const data = JSON.parse(fs.readFileSync(jsonFile, "utf-8"));
      const allTags = new Set();
      data.forEach((feature) => {
        if (feature.tags) {
          feature.tags.forEach((t) => allTags.add(t.name));
        }
      });

      if (allTags.size > 0) {
        return Array.from(allTags).join(", ");
      }

      if (data.length === 1 && data[0].name) {
        return data[0].name;
      }
    } catch (e) {
      // Ignore parse errors
    }
  }

  // Fallback to environment variables
  if (process.env.TAGS) return process.env.TAGS;
  if (process.env.FEATURE_PATH) return path.basename(process.env.FEATURE_PATH, ".feature");

  return "HYR Tutorials Automation";
}

const projectName = getRunDisplayName();

report.generate({
  jsonDir: jsonDir,
  reportPath: reportPath,
  metadata: {
    browser: {
      name: browser,
      version: "latest",
    },
    device: "Local test machine",
    platform: {
      name: platformName,
      version: platformVersion,
    },
  },
  customData: {
    title: "Run Info",
    data: [
      { label: "Project", value: projectName },
      { label: "Release", value: "1.0.0" },
      { label: "Generated", value: new Date().toLocaleString() },
    ],
  },
  pageFooter: '<div class="created-by"><p>Generated by TS Playwright Cucumber Framework :: SaiTeja Goud</p></div>',
});

const htmlReport = path.join(reportPath, "index.html");

console.log("\n✅ Cucumber HTML report generated:");
console.log("  " + htmlReport + "\n");

// Archive the newly generated report
archiveReports();